import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "../components/HOC/StoreProvider";
import Sidebar from "@/components/Sidebar";
import ThemeProvider from "@/components/HOC/ThemeProvider";
import Navbar from "@/components/Navbar";
import ApolloAppProvider from "@/components/HOC/ApolloAppProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ApolloAppProvider>
                <StoreProvider>
                    <body className="">
                        <ThemeProvider>
                            <div className="flex w-full min-h-screen bg-light-bg dark:bg-dark-bg font-main text-gray-800 dark:text-gray-300">
                                <Sidebar />
                                <div className="md:ml-40 lg:ml-[25%] w-full lg:w-8/12 xl:w-1/2  p-6 sm:p-12 h-full">
                                    <Navbar />
                                    {children}
                                </div>
                            </div>
                        </ThemeProvider>
                    </body>
                </StoreProvider>
            </ApolloAppProvider>
        </html>
    );
}
