version: "3.4"

services:
  postgres:
    container_name: visionex-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: visionex
      POSTGRES_PASSWORD: visionex

  redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
